import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Jepzec",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="font-poppins scroll-smooth bg-linear-to-b from-gray-500 to-black text-white"
    >
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
