import type { Metadata } from "next";
import Image from "next/image";

import "./globals.css";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Jepzec",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="scroll-smooth font-poppins bg-linear-to-b from-gray-500  to-black text-white "
    >
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
